version: '3.5'

services:

  php-apache:
    container_name: php-apache
    image: webdevops/php-apache:7.4
    volumes:
      - .:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
    ports:
      - 80:80
    depends_on:
      - database

  database:
    container_name: database
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=php_tarefas
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    links:
      - database
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1G

volumes:
    database: